### ISSUE TITLE
Nested buckets support?

### ISSUE THREAD

**Issue by falzm** [djherbis/stow#9]
Hi

I'm new to BoltDB/Stow, and I'd like to know if it is possible to create BoltDB nested buckets (https://github.com/boltdb/bolt#nested-buckets) using Stow? If yes, could you give me a hint?

**Comment by djherbis** [comment]
I don't currently support creating nested buckets in stow. However its pretty easy to create a nested bucket with boltdb and wrap it it in stow.NewStore.

Whats your use case? Would it be really helpful if stow supported this directly?

**Comment by falzm** [comment]
My use case is: for monitoring purpose I'd like to store *checks* states for *agents* in BoltDB, and I'm still trying to find a way to lay out data to be stored in BoltDB. Typically, there are serveral agents – up to hundreds –, and an *agent* has several *checks* – up to dozens, most likely – such as:

```go
type Check struct {
  <check properties>
}

type Agent struct {
  checks map[string]*Check
}

type Store struct {
  agents map[string]*Agent
}
```

I'm looking for a way to persist this data in BoltDB, and I figured nesting buckets to simulate maps would be a practical way to iterate over entries using `ForEach()`, in a similar fashion to `range` over a Go map. However not being experienced in using BoltDB I might be totally wrong :)

**Comment by djherbis** [comment]
That seems like a reasonable use case.

I think I'll add explicit support for nested buckets to stow. I can see that there isn't a workaround now (I only support top-level buckets at the moment). I'll try to add it over the weekend.

Couple issues though: I'm currently avoiding exposing transactions in stow. In order to keep it simple, I just have singular, persistent, atomic operations. If you need all of these operations to be transactional together, then you might be better off using raw [bolt](github.com/boltdb/bolt) or [thunder](github.com/omeid/thunder).

**Comment by falzm** [comment]
I'm afraid I don't know BoltDB enough to see the difference at this point, just do it as you see fit – it's already nice of you to consider adding this feature.

**Comment by djherbis** [comment]
The latest version [v2.2.0](https://github.com/djherbis/stow/releases/tag/v2.2.0) supports this feature.

**Comment by djherbis** [comment]
@falzm Please confirm if this update suits your needs.
